Sort wines by version numbers

diff --git a/rum b/rum
--- a/rum
+++ b/rum
@@ -3,11 +3,11 @@
 wines="/opt/wines"
 
 error() { echo -e "$@"; exit 1 ;}
-[[ $# -lt 3 ]] && error "Not enough arguments!\nUsage: rum <wine-version or /path/to/wine/version> </path/to/wine/prefix> <wine command> [wine arguments...]\n\nWine versions available:\n$(ls $wines)"
+[[ $# -lt 3 ]] && error "Not enough arguments!\nUsage: rum <wine-version or /path/to/wine/version> </path/to/wine/prefix> <wine command> [wine arguments...]\n\nWine versions available:\n$(ls $wines | sort --version-sort)"
 
 winepath="$1"; shift
 export WINEPREFIX="$(readlink -f $1)";  shift
-[[ -d "$winepath" ]] || [[ -d "$wines/$winepath" ]] && winepath="$wines/$winepath" || error "Error! Path to wine version doesn't exist!\nWine versions available:\n$(ls $wines)"
+[[ -d "$winepath" ]] || [[ -d "$wines/$winepath" ]] && winepath="$wines/$winepath" || error "Error! Path to wine version doesn't exist!\nWine versions available:\n$(ls $wines | sort --version-sort)"
 if [[ ! -d "$WINEPREFIX" ]]; then
 	read -p "Wine prefix doesn't exist, do you want to create it? [Y/n] " -s -n 1 -r
 	echo
